### ISSUE TITLE
Convert Bgen to Correct VCF and correct file format to prevent Null objects

### ISSUE THREAD

**Issue by carolynmcgrail** [mvaudel/diabetesRiskScores#1]
Hello, 

I have pulled out the T1D GRS1 snps  from genotype data stored in .bgen files and converted them to a vcf 4.2 file using plink2 which I think should be compatible with diabetesRiskScores: 

`plink2 --bgen GS1_snps.bgen ref-first --sample GRS.sample --export vcf-4.2 bgz --out GS1_snps`

I tried to run making the Info file for the vcf using: 

`java -cp /home/cmcgrail/diabetesRiskScores/bin/drs-0.0.1/drs-0.0.1.jar no.uib.drs.cmd.InfoFile -g /data5/ukbb_IMPUTE2_GRS/GRS1_ukbb_snps_4.2.vcf.gz -o /data5/ukbb_IMPUTE2_GRS/GRS1_ukbb_snps_DRS.info.gz -t TYPED -f 0 -s INFO 
`

but am receiving this error and I'm not sure if this is a vcf incompatibility and how to remedy this since the original genotype data are stored in bgen files.  

```
java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "htsjdk.variant.variantcontext.VariantContext.getAttribute(String)" is null
	at no.uib.drs.cmd.InfoFile.extractDetails(InfoFile.java:177)
	at no.uib.drs.cmd.InfoFile.writeInfoFile(InfoFile.java:99)
```

It looks like there is a compatibility issue with the vcf file, but I believe that vcf4.2 version should work with samtools. Is there a way you would suggest pulling the snps from bgen files and converting this to vcf files that would allow this to run? Thank you for your help.

Best,
Carolyn

**Comment by mvaudel** [comment]
Dear Carolyn,

Thank you for reporting this issue. You are correct, it seems that the tool is looking for a field that is missing in this vcf. So far, we only tested the tool on vcfs produced by imputation servers.

I have to say that we have not used this code in a long time and stopped using vcf files altogether. Instead, for T1D scores, we just extract the genotypes of the relevant variants using plink and compute the scores in python or R.

I can look into updating the code to work with bgen directly, but we are currently low in manpower so it is difficult to give an ETA on this.

Apologies that I cannot help more at this stage,

Marc

**Comment by carolynmcgrail** [comment]
Hey Marc,

Thanks so much for your reply! I figured it was an issue with the VCF format and also went to manually extracting genotypes and calculating GRS with python. Thanks for your help! 

Best,
Carolyn
